spring:
  application:
    name: lsx-service-test


server:
  port: 18882


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:18881/eureka
  instance:
    prefer-ip-address: true





debug: true
