spring:
  application:
    name: lsx-service-device
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/lsx-web?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: QWER1234
  redis:
    host: localhost
    port: 16379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
    # 时区设置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: localhost
    port: 5672
    username: springboot-admin
    password: admin

server:
  port: 18887


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:18881/eureka

#本地证书和密钥密码配置
#公钥加密   --  私钥解密   ---》非对称加密算法，RSA
encrypt:
  key-store:
    #证书路径
    location: classpath:/lsx.jks
    #证书的密钥
    secret: lsxlsx
    #证书的别名
    alias: lsx
    #证书的密码
    password: lsxlsx

#debug: true
#logging:
#  level:
#    root: debug


zookeeper:
  address: 127.0.0.1:2181
  timeout: 4000



