spring:
  application:
    name: lsx-service-device
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/lsx-web?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: QWER1234
  redis:
    host: localhost
    port: 16379
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true

server:
  port: 18887


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:18881/eureka

#本地证书和密钥密码配置
#公钥加密   --  私钥解密   ---》非对称加密算法，RSA
encrypt:
  key-store:
    #证书路径
    location: classpath:/lsx.jks
    #证书的密钥
    secret: lsxlsx
    #证书的别名
    alias: lsx
    #证书的密码
    password: lsxlsx

debug: true
logging:
  level:
    root: debug
