spring:
  servlet:
    multipart:
      max-file-size: 10MB     #上传文件大小
      max-request-size: 10MB  #请求大小
  application:
    name: lsx-service-file
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/lsx-web?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: QWER1234
    ### 数据源类别
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 16379

server:
  port: 18885

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18881/eureka
  instance:
    prefer-ip-address: true

fastdfs:
  server:
    url: http://10.211.55.10:8080/


debug: true
